=begin
Niche API

REST API to access gridded climate model data at specific points in time.  Developed specifically to support Ice Age Mapper / Niche Viewer, and to tie into morphospace visualizations of NeotomaDB data. Enables users to select climate data at single space-time points, arrays of space-time points, or time series at single points.  University of Wisconsin, Madison Department of Geography.

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'date'

module SwaggerClient
  class Variable
    # What the variable represents
    attr_accessor :variable_type

    # How the variable is measured
    attr_accessor :variable_units

    # Period that the variable represents
    attr_accessor :variable_period

    # Type of period represented by the variable
    attr_accessor :variable_period_type

    # Period over which the variable is averaged.
    attr_accessor :averaging_period

    # Type of period over which the variable is average.
    attr_accessor :averaging_period_type

    # Database ID of the variable
    attr_accessor :variable_id

    # Plain text description of the variable.
    attr_accessor :variable_description

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        
        :'variable_type' => :'variableType',
        
        :'variable_units' => :'variableUnits',
        
        :'variable_period' => :'variablePeriod',
        
        :'variable_period_type' => :'variablePeriodType',
        
        :'averaging_period' => :'averagingPeriod',
        
        :'averaging_period_type' => :'averagingPeriodType',
        
        :'variable_id' => :'variableID',
        
        :'variable_description' => :'variableDescription'
        
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'variable_type' => :'String',
        :'variable_units' => :'String',
        :'variable_period' => :'Integer',
        :'variable_period_type' => :'String',
        :'averaging_period' => :'Integer',
        :'averaging_period_type' => :'String',
        :'variable_id' => :'Integer',
        :'variable_description' => :'String'
        
      }
    end

    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.inject({}){|memo,(k,v)| memo[k.to_sym] = v; memo}

      
      if attributes[:'variableType']
        self.variable_type = attributes[:'variableType']
      end
      
      if attributes[:'variableUnits']
        self.variable_units = attributes[:'variableUnits']
      end
      
      if attributes[:'variablePeriod']
        self.variable_period = attributes[:'variablePeriod']
      end
      
      if attributes[:'variablePeriodType']
        self.variable_period_type = attributes[:'variablePeriodType']
      end
      
      if attributes[:'averagingPeriod']
        self.averaging_period = attributes[:'averagingPeriod']
      end
      
      if attributes[:'averagingPeriodType']
        self.averaging_period_type = attributes[:'averagingPeriodType']
      end
      
      if attributes[:'variableID']
        self.variable_id = attributes[:'variableID']
      end
      
      if attributes[:'variableDescription']
        self.variable_description = attributes[:'variableDescription']
      end
      
    end

    # Check equality by comparing each attribute.
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          variable_type == o.variable_type &&
          variable_units == o.variable_units &&
          variable_period == o.variable_period &&
          variable_period_type == o.variable_period_type &&
          averaging_period == o.averaging_period &&
          averaging_period_type == o.averaging_period_type &&
          variable_id == o.variable_id &&
          variable_description == o.variable_description
    end

    # @see the `==` method
    def eql?(o)
      self == o
    end

    # Calculate hash code according to all attributes.
    def hash
      [variable_type, variable_units, variable_period, variable_period_type, averaging_period, averaging_period_type, variable_id, variable_description].hash
    end

    # build the object from hash
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          else
            #TODO show warning in debug mode
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        else
          # data not found in attributes(hash), not an issue as the data can be optional
        end
      end

      self
    end

    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        _model = SwaggerClient.const_get(type).new
        _model.build_from_hash(value)
      end
    end

    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_body (backward compatibility))
    def to_body
      to_hash
    end

    # return the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Method to output non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
