## Niche API Swagger Spec
## Author: Scott Farley
## Created: 6/13/2016
## Edited: 11/21/2016
swagger: '2.0' ## use this version of swagger
info:
  title: Niche API
  description: Simple REST API to access climate data at specific points in space and time.  Developed at UW Madison, Geography.
  version: "2.0.0" ## version 2 uses node bindings
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /variables:
    # binds a127 app logic to a route
    x-swagger-router-controller: variables
    get:
      description: Returns a list of the variables available in the database to the user.
      operationId: getVariables
      parameters:
        - name: variableType
          in: query
          description: Variable type ID by which to filter results
          required: false
          type: integer
          
        - name: variablePeriod
          in: query
          description: Variable period filter (e.g., 1)
          required: false
          type: integer
        
        - name: variablePeriodType
          in: query
          description: Variable period type specification (e.g., month)
          required: false
          type: string
        
        - name: averagingPeriod
          in: query
          description: Period over which the variable has been averaged
          required: false
          type: integer
        
        - name: averagingPeriodType
          in: query
          description: Type of period over which the variable has been averaged.
          required: false
          type: integer
          
        - name: variableUnits
          in: query
          description: Units in which the variable is measured.
          required: false
          type: integer
        
        - name: variableID
          in: query
          description: Database ID of the variable 
          required: false
          type: integer
          
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/VariableResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /swagger:
    x-swagger-pipe: swagger_raw
    
  /timeseries:
    x-swagger-router-controller: timeseries
    get:
      description: Get all time points in the database at a single space location for a single variable
      operationId: getTimeseries
      parameters:
        - name: latitude
          required: true
          type: number
          description: Latitude of POI
          in: query
        - name: longitude
          required: true
          type: number
          description: Longitude of POI
          in: query
        - name: variableID
          required: true
          type: number
          description: Database ID of variable of interest
          in: query
        - name: sourceID
          required: true
          type: number
          description: Database ID of source of interest
          in: query
      responses:
        "200": 
          description: Success
          schema: 
            $ref: "#/definitions/TimeSeriesResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /data:
    x-swagger-router-controller: data
    get:
      description: Get data for a single space-time point for a since single source and variable
      operationId: getDataPoint
      parameters:
        - name: latitude
          required: true
          type: number
          description: Latitude of POI
          in: query
        - name: longitude
          required: true
          type: number
          description: Longitude of POI
          in: query
        - name: variableID
          required: true
          type: number
          description: Database ID of variable of interest
          in: query
        - name: sourceID
          required: true
          type: number
          description: Database ID of source of interest
          in: query
        - name: yearsBP
          required: true
          type: number
          description: years before present of data point
          in: query
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/DataResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      operationId: postData
      description: Get data for an array of space-time points for a single source and variable
      parameters:
        - name: data
          schema:
            $ref: "#/definitions/PostDataRequest"
          in: body
          required: false
          description: An array of space-time locations to get data for.
      responses:
        "200":
          description: Success
          schema: 
            $ref: "#/definitions/DataResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /variableTypes:
    x-swagger-router-controller: variableTypes
    get:
      description: Get a list of the variable types in the database.
      operationId: getVariableTypes
      parameters:
        - name: variableTypeId
          required: false
          type: number
          description: Database ID of the variable type
          in: query
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /variablePeriodTypes:
    x-swagger-router-controller: variablePeriodTypes
    get:
      description: Get a list of the time periods a variable could represent.
      operationId: getVariablePeriodTypes
      parameters:
        - name: variablePeriodTypeId
          required: false
          type: number
          description: Database ID of the variable period type
          in: query
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"  
            
            
  /averagingPeriodTypes:
    x-swagger-router-controller: averagingPeriodTypes
    get:
      description: Get a list of the time periods over which a variable could be averaged.
      operationId: getAveragingPeriodTypes
      parameters:
        - name: averagingPeriodTypeId
          required: false
          type: number
          description: Database ID of the averaging period type.
          in: query
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
            
  /sources:
    x-swagger-router-controller: sources
    get:
      description: Get a list of sources in the database.
      operationId: getSources
      parameters:
        - name: sourceId
          required: false
          type: number
          description: Database ID of the source.
          in: query
          
        - name: scenario
          required: false
          type: number
          description: Emission scenario under which the model was run.
          in: query
        
        - name: version
          required: false
          type: number
          description: The version of the modeling product.
          in: query
          
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"         
        
        
# complex objects have schema definitions
definitions:
  Variable:
    required: 
      - variableType
      - variableUnits
      - variablePeriod
      - variablePeriodType
      - averagingPeriod
      - averagingPeriodType
      - variableID
      - variableDescription
    properties: 
      variableType:
        description: What the variable represents
        type: string
      variableUnits:
        description: How the variable is measured
        type: string
      variablePeriod:
        description: Period that the variable represents
        type: integer
      variablePeriodType:
        description: Type of period represented by the variable
        type: string
      averagingPeriod:
        description: Period over which the variable is averaged.
        type: integer
      averagingPeriodType:
        description: Type of period over which the variable is average.
        type: string
      variableID:
        type: integer
        description: Database ID of the variable
      variableDescription:
        type: string
        description: Plain text description of the variable.
  
  TimeSeriesPoint:
    properties:
      id: 
        type: integer
      value:
        type: number
      time:
        type: number
        
  TimeSeriesResponse:
    required:
      - success
      - timestamp
      - latitude
      - longitude
      - data
    properties:
      success:
        type: boolean
        description: Flag to indicate whether the server responded successfully.
      timestamp:
        type: string
        format: date-time
        description: Time at which the response was minted by the server
      latitude:
        type: number
        format: float
      longitude:
        type: number
        format: float
      variable:
        $ref: "#/definitions/Variable"
      data:
        type: array
        items:
          $ref: "#/definitions/TimeSeriesPoint"
  
  GenericResponse:
    properties:
      success: 
        type: boolean
        description: Flag to indicate whether the server responded successfully.
      timestamp:
        type: string
        format: date-time
        description: Time at which the response was minted by the server
      data:
        type: array
        items:
          type: object
          
  DataPoint:
    properties:
      year:
        type: integer
        description: Year before present represented by the response
      above: 
        type: number
        description: Value of the time slice above the year in the interpolation
      below:
        type: number
        description: Value of the time slice below the year in the interpolation
      yearAbove:
        type: integer
        description: Year above in the interpolation
      yearBelow:
        type: integer
        description: Year below in the interpolation
      interp:
        type: number
        description: Interpolated variable value between the yearAbove and the yearBelow
      latitude: 
        type: number
        description: Latitude of POI
      longitude:
        type: number
        description: Longitude of POI
        
  DataResponse:
    properties:
      success:
        type: boolean
        description: Flag to indicate whether the server responded successfully.
      timestamp:
        type: string
        format: date-time
        description: Time at which the response was minted by the server
      variableID:
        type: integer
        description: Variable represented by the response
      sourceID:
        type: integer
        description: Data source of the response
      data:
        type: array
        items:
          $ref: "#/definitions/DataPoint"
      
  VariableResponse:
    required:
      - success
      - timestamp
      - data
    properties:
      success:
        type: boolean
        description: Flag to indicate whether the server responded successfully.
      timestamp:
        type: string
        format: date-time
        description: Time at which the response was minted by the server
      data:
        type: array
        items:
          # $ref: "#/definitions/Variable"
          type: object
        
  ErrorResponse:
    properties: 
      error:
        type: object
        
  PointRequest:
    required:
     - latitude
     - longitude
     - year
    properties:
      latitude:
        type: number
        description: Latitude of POI
      longitude:
        type: number
        description: Longitude of POI
      year:
        type: integer
        description: Years before present of location of interest
      id:
        type: integer
        description: Optional ID number for relating to neotoma or other site identifiers.
  
  PostDataRequest:
    properties:
      points:
        type: array
        items:
          $ref: "#/definitions/PointRequest"
      variableID:
        type: integer
        description: Database ID for the requested variable
      sourceID:
        type: integer
        description: Database ID for the requested data source
            

        
